Add ServiceMonitor capability for Prometheus Operator
google-cloud-tools/kube-eagle-helm-chart pull request #1
Opened 2019-03-04 07:34 UTC by rebelthor

Prometheus operator changes the way metrics are discovered by not using annotations and rather creating a Custom Resource of ServiceMonitor type: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources

This merge request adds capability to create a ServiceMonitor custom Resource so that when enabled, Prometheus Operator will automatically discover metrics exposed by kube-eagle

2019-03-05 18:02 UTC, weeco requested changes
Thanks for your pull request, looks good :). I believe the metadata label release should be the chart's Release.Name

2019-03-05 18:02 UTC, weeco commented on kube-eagle/templates/servicemonitor.yaml
> +    release: prometheus-operator
This should be `{{ .Release.Name }}` shouldn't it?

2019-03-06 07:33 UTC, rebelthor commented on kube-eagle/templates/servicemonitor.yaml
> +    release: prometheus-operator
The problem with the release label is that the Prometheus Operator [uses a label selector to decide which ServiceMonitors to check](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#include-servicemonitors), in the idea that you may have several prometheuses installed and this provides a way to assign ServiceMonitors to specific Prometheuses.

The default chart installation of Prometheus Operator comes with this configuration:
`prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues = true
prometheus.prometheusSpec.serviceMonitorSelector = {}`

Due to this and the prometheus operator chart template in https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L69-L75 , the selector ends up being actually the prometheus operator release name:

`  Service Monitor Selector:
    Match Labels:
      Release:  prometheus-operator`

To improve this, I will update this merge request shortly by parameterizing the release label (with a default of prometheus-operator which seems like a sensible default, and also with an additional label value to support custom prometheus operator Match Labels, in which case the release would then be allowed to be {{ .Release.Name }}.

2019-03-06 09:50 UTC, rebelthor commented on kube-eagle/templates/servicemonitor.yaml
> +    release: prometheus-operator
I've submitted a new commit which addresses this aspect. Thanks!

2019-03-06 23:36 UTC, merged

2019-03-06 23:42 UTC, weeco commented
Merged! Thanks a lot for your effort @rebelthor, I just repackaged it (updated repo index.yaml was missing).